language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.6.5

before_install:
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  - docker run -d -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch:6.3.0

install:
  - python setup.py install

script:
  - python setup.py test
