clusters:
  default:
    hosts: ['http://192.168.99.100:9200']
#    auth:
#      username: 'elastic'
#      password:
#        ask: yes
#        value: 'elastic'
#    ssl:
#      enabled: no
#      cert: 'some_cer'
#      ca: ''
#      private_key: ''
#      verify_certs: yes
#    timeout: '30s'

  default2:
    hosts: ['http://localhost:9300']
